// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFJRnfqVdV-Mkn1-cY5okrXNsmIr-Ozs',
    appId: '1:134067255517:android:84d0a467c07d3a073ec334',
    messagingSenderId: '134067255517',
    projectId: 'gocrispy-b5cfd',
    storageBucket: 'gocrispy-b5cfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL4F-s8pe-jJzUzQG1aADEXk5dFHRSq98',
    appId: '1:134067255517:ios:0cd1808974ec2b653ec334',
    messagingSenderId: '134067255517',
    projectId: 'gocrispy-b5cfd',
    storageBucket: 'gocrispy-b5cfd.appspot.com',
    iosBundleId: 'com.artisans.go-crispy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDolvZqtrgGAuRikWEhL3kHoG8FmamWKIA',
    appId: '1:134067255517:web:63a603371f28714d3ec334',
    messagingSenderId: '134067255517',
    projectId: 'gocrispy-b5cfd',
    authDomain: 'gocrispy-b5cfd.firebaseapp.com',
    storageBucket: 'gocrispy-b5cfd.appspot.com',
    measurementId: 'G-017ZV8D8QR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL4F-s8pe-jJzUzQG1aADEXk5dFHRSq98',
    appId: '1:134067255517:ios:568381c33c0a2c513ec334',
    messagingSenderId: '134067255517',
    projectId: 'gocrispy-b5cfd',
    storageBucket: 'gocrispy-b5cfd.appspot.com',
    iosBundleId: 'com.sixamtech.userAppAndWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDolvZqtrgGAuRikWEhL3kHoG8FmamWKIA',
    appId: '1:134067255517:web:a1ad62116cba0e933ec334',
    messagingSenderId: '134067255517',
    projectId: 'gocrispy-b5cfd',
    authDomain: 'gocrispy-b5cfd.firebaseapp.com',
    storageBucket: 'gocrispy-b5cfd.appspot.com',
    measurementId: 'G-TVXMQKG6CD',
  );

}